### ISSUE TITLE
demo 效果

### ISSUE THREAD

**Issue by suzhenghang** [WelkinYang/Learn2Sing2.0#3]
我看demo的效果，student合成效果，有些词不太准而且有走音现象

**Comment by WelkinYang** [comment]
无法完全赶上Teacher水平，但在Related work(目标说话人只有说话数据的情况)中效果是最好的，很多方法只在英文上work中文上完全无法复现或者表现无法参与评价，所以我们没有在论文中比较其他方法，有兴趣可以尝试一下其他方法。
